### ISSUE TITLE
slow adjoint compared to forward transform

### ISSUE THREAD

**Issue by ghisvail** [NFFT/nfft#10]
We are currently considering to use the MATLAB wrappers of NFFT 3.3 to update our MRI reconstruction toolchain. However, our benchmarks are showing that the adjoint can be significantly slower than the forward transformation for no obvious reasons.

On a 256^2 image grid (N) with 256^2 radial k-space points (M) with full precomputation, we get the following timings:
precomputation: 75 ms
forward transform: 27 ms
adjoint transform: 206 ms
forward direct: 210s
adjoint direct: 207s
...repeated over a dozen of trials to average out potential slow down due to cache misses, schedulers and stuff.

Compared to our reference implementation (Greengard's NUFFT), the forward transform is much faster, but the adjoint is significantly slower. Since our reconstructions rely on iterative solvers doing back and forth transforms, this is quite an issue for us. On average, successive forward and adjoint transforms are faster with Greengard's implementation (which uses no precomputation) than NFFT.

Are you guys aware of performance problems with adjoint versus forward transforms ?

**Comment by jenskeiner** [comment]
I'm aware that the adjoint transformation is slower, but not under which circumstances the difference is substantial. We should check this and improve where we can.

I reckon it could have to do with how we iterate over the data structures, especially the pre-computed ones.

As a first step, I would look into how long the application of the matrix B takes. That's the most complicated one anyway.

**Comment by jenskeiner** [comment]
At first check, I wasn't able to reproduce slower adjoint transforms. If anything, the adjoint transformation was faster.

Please post some details on which parameters you use: configure flags, window function, transformation sizes N[...] and M, nfft_init() function used, NFFT and FFTW flags used, etc.

**Comment by ghisvail** [comment]
Ok I'll ask my colleague who ran the benchmarks to post his MATLAB script together with the config flags he used to build the library with.

**Comment by aitkenap** [comment]
Hi, I have investigated the problem further, it seems to be an issue with the matlab-threads option. With matlab-threads disabled, the forward and adjoint take approximately the same time. The openmp option seems to make no difference, as I would expect. With matlab-threads enabled, both the precomputation and forward transform are faster, but the adjoint is now much slower.

So for the following flags:

--disable-static --disable-openmp --disable-matlab-threads --with-matlab=/usr/local/MATLAB/R2014a
--disable-static --enable-openmp --disable-matlab-threads --with-matlab=/usr/local/MATLAB/R2014a

I have these run times:
3D NFFT:
precomp: 1.3 s
fwd: 3 s
adj: 3 s

And with these flags:
--disable-static --enable-openmp --enable-matlab-threads --with-matlab=/usr/local/MATLAB/R2014a

I get these run times:
3D NFFT:
precomp: 0.4 s
fwd: 1.4 s
adj: 10.3 s

I'm using an Intel Core i7-2620 with Mint 17, 2 cores, 4 threads. With matlab-threads enabled, top tells me it's running close to 400%, without it's at 100%.

The matlab code I'm using to test is below:

```matlab
clear all
close all

%% Parameters

N = 64;
n = N;
M = 6;
n_reps = 1; % Number of times to run the fwd/adj tests

dims = 3;   % 2 or 3 for 2D/3D transform
DO_DFT = false; 

%% Initialize

switch dims
    case 2
        img = complex(phantom(N));
        plan = nfft(2,[N;N],N^2,n,n,M,'PRE_PHI_HUT','FFTW_MEASURE','PRE_FULL_PSI');
        
    case 3
        img = repmat(complex(phantom(N)),[1 1 N]);
        plan = nfft(3,[N;N;N],N^3,n,n,n,M,'PRE_PHI_HUT','FFTW_MEASURE','PRE_FULL_PSI');
        
    otherwise
        error('dims must be 2 or 3')
        
end

k = (rand(N^dims,dims)-0.5)*(1-eps);

plan.x = k;

%% NFFT

display(['NFFT (' num2str(dims) 'D):'])

% Precomputation
t_precomp_start = tic;
nfft_precompute_psi(plan);
t_precomp = toc(t_precomp_start);

display(['Time for precomp: ' num2str(t_precomp) ' s'])

for ii = 1:n_reps
    
    % Forward
    plan.fhat = img(:);
    t_fwd_nfft3_start = tic ;
    nfft_trafo(plan);
    t_fwd_nfft3 = toc(t_fwd_nfft3_start);
    display(['Time for fwd nfft3: ' num2str(t_fwd_nfft3) ' s'])
    
    % Adjoint
    t_adj_nfft3_start = tic;
    nfft_adjoint(plan);
    t_adj_nfft3 = toc(t_adj_nfft3_start);
    display(['Time for adj nfft3: ' num2str(t_adj_nfft3) ' s'])
    
end


%% Direct

if DO_DFT
    display(['NDFT (' num2str(dims) 'D):'])
    
    % Forward
    plan.fhat = img(:);
    t_fwd_ndft3_start = tic;
    ndft_trafo(plan);
    t_fwd_ndft3 = toc(t_fwd_ndft3_start);
    display(['Time for fwd ndft3: ' num2str(t_fwd_ndft3) ' s'])
    
    % Adjoint
    t_adj_ndft3_start = tic;
    ndft_adjoint(plan);
    t_adj_ndft3 = toc(t_adj_ndft3_start);
    display(['Time for adj ndft3: ' num2str(t_adj_ndft3) ' s'])
    
end
```

**Comment by tvolkmer** [comment]
@aitkenap Thank you for providing the matlab test code.

First one remark : We usually denote the window cut-off parameter by little 'm' (in your example m=6) and the number of non-equispaced nodes by capital 'M' (M=N^d in your test code).

Moreover, we suggest to use an oversampling factor sigma>1 in general except for special situations. For instance with sigma=1.25,this means setting the FFTW length parameter n to sigma * N=1.25*N. For the NFFT library, the FFTW length parameter n has to be an even integer.  Since the FFTW should be faster when n is a power of 2, one might set n=2^(ceil(log2(1.25*N))).

In general, the nfft flag PRE_PSI should be set instead of PRE_FULL_PSI. Using the PRE_FULL_PSI flag requires a HUGE amount of RAM and a lot of precomputation time, whereas the improvement in the runtime (compared to PRE_PSI) may be small. If the flag PRE_FULL_PSI is set in the test code, a matrix of type double with M*(2*m+2)^d entries is created. In the case d=3,N=64,m=6,M=64^3 this means about 720 million entries and about 6GB of RAM.
The flag PRE_PSI uses a tensor product approach and only creates M*(2*m+2)*d entries, here about 11 million entries and about 90MB of RAM.

The plan initialization in the test code,
```
plan = nfft(3,[N;N;N],N^3,n,n,n,m,'PRE_PHI_HUT','FFTW_MEASURE','PRE_FULL_PSI');
```
which can be found in a comment in the nfft.m file or in our examples test_nfft2d.m / test_nfft3d.m, does not work correctly. The nfft class constructor expects the parameters nfft_flags and fftw_flags as an integer bit mask, not as a string. I think we did not really document this properly. I'm going to correct these misleading code snippets in the comments in the Matlab files.
The correct plan initialization for the case d=3 would be:
```
plan = nfft(3,[N;N;N],N^3,n,n,n,m,bitor(PRE_PHI_HUT,PRE_FULL_PSI),FFTW_MEASURE);
```

Another issue with the current NFFT code is that if the advanced constructor (additional parameters n, m, nfft_flags,fftw_flags) is used, which itself calls the nfft_init_guru function, some nfft flags are not set by default which would be set by the simple class constructor
```
plan = nfft(3,N,M);
```
One important missing nfft flag is NFFT_OMP_BLOCKWISE_ADJOINT, which is currently not defined for the Matlab interface but only in the nfft3.h file:
```
#define NFFT_OMP_BLOCKWISE_ADJOINT (1U<<12)
```
When setting this flag and enabling OpenMP support, a (usually) faster implementation is called for the adjoint NFFT in the cases d>=2.

Using a modified version of the test code with the nfft flags PRE_PSI and NFFT_OMP_BLOCKWISE_ADJOINT (value 2^12=4096), I obtain the following results on computer with an Intel i7-970 CPU and 24 GB RAM enabling matlab-threads and using 4 threads:
```
NFFT (3D, 4 threads):
Time for precomp: 0.29879 s
Time for fwd nfft3: 0.83857 s
Time for adj nfft3: 0.99962 s
```
Setting only PRE_PSI (and PRE_PHI_HUT) with 4 threads:
```
NFFT (3D, 4 threads):
Time for precomp: 0.25683 s
Time for fwd nfft3: 1.7853 s
Time for adj nfft3: 4.1396 s
```
Setting the flags PRE_PSI and NFFT_OMP_BLOCKWISE_ADJOINT but disabling matlab-threads:
```
NFFT (3D, 1 threads):
Time for precomp: 1.0641 s
Time for fwd nfft3: 3.1114 s
Time for adj nfft3: 3.72 s
```
Matlab requires totally about 500MB RAM during the computations on 64 bit Linux (Flag PRE_PSI)

Just for comparison the runtimes when setting the flags PRE_FULL_PSI and NFFT_OMP_BLOCKWISE_ADJOINT when enabling matlab-threads and using 4 threads are:
```
NFFT (3D, 4 threads):
Time for precomp: 20.1509 s
Time for fwd nfft3: 1.439 s
Time for adj nfft3: 1.8208 s
```
setting the flags PRE_FULL_PSI and NFFT_OMP_BLOCKWISE_ADJOINT, disabling matlab-threads:
```
NFFT (3D, 1 threads):
Time for precomp: 76.7381 s
Time for fwd nfft3: 3.3933 s
Time for adj nfft3: 3.6661 s
```
Matlab requires totally about 12GB RAM during the computations (Flag PRE_FULL_PSI).

Here, the adjoint NFFT without OpenMP/threads setting PRE_FULL_PSI or PRE_PSI have almost the same runtime (~3.7s). When using 4 threads, the adjoint NFFT with PRE_PSI is about twice as fast (PRE_PSI ~1.0s vs. PRE_FULL_PSI ~1.8s)

@aitkenap Here is the modified Matlab test code which should work better:
```
clear all
close all

%% Parameters

N = 64;
sigma = 1.25;  % oversampling factor, typically >1
n = 2^(ceil(log2(sigma*N)));  % FFTW length, must be even integer, power of 2 suggested
m = 6;
n_reps = 1; % Number of times to run the fwd/adj tests

dims = 3;   % 2 or 3 for 2D/3D transform
DO_DFT = false; 

%% Initialize

switch dims
    case 2
        img = complex(phantom(N));
        % use nfft_flags PRE_PHI_HUT, PRE_PSI, NFFT_OMP_BLOCKWISE_ADJOINT (=2^12=4096)
        plan = nfft(2,[N;N],N^2,n,n,m,bitor(PRE_PHI_HUT,bitor(PRE_PSI,4096)),FFTW_MEASURE);

    case 3
        img = repmat(complex(phantom(N)),[1 1 N]);
        % use nfft_flags PRE_PHI_HUT, PRE_PSI, NFFT_OMP_BLOCKWISE_ADJOINT (=2^12=4096)
        plan = nfft(3,[N;N;N],N^3,n,n,n,m,bitor(PRE_PHI_HUT,bitor(PRE_PSI,4096)), ...
        FFTW_MEASURE);

    otherwise
        error('dims must be 2 or 3')

end

k = (rand(N^dims,dims)-0.5)*(1-eps);

plan.x = k;

%% NFFT

display(['NFFT (' num2str(dims) 'D, ' num2str(nfft_get_num_threads()) ' threads):'])

% Precomputation
t_precomp_start = tic;
nfft_precompute_psi(plan);
t_precomp = toc(t_precomp_start);

display(['Time for precomp: ' num2str(t_precomp) ' s'])

for ii = 1:n_reps

    % Forward
    plan.fhat = img(:);
    t_fwd_nfft3_start = tic ;
    nfft_trafo(plan);
    t_fwd_nfft3 = toc(t_fwd_nfft3_start);
    display(['Time for fwd nfft3: ' num2str(t_fwd_nfft3) ' s'])

    % Adjoint
    t_adj_nfft3_start = tic;
    nfft_adjoint(plan);
    t_adj_nfft3 = toc(t_adj_nfft3_start);
    display(['Time for adj nfft3: ' num2str(t_adj_nfft3) ' s'])

end


%% Direct

if DO_DFT
    display(['NDFT (' num2str(dims) 'D):'])

    % Forward
    plan.fhat = img(:);
    t_fwd_ndft3_start = tic;
    ndft_trafo(plan);
    t_fwd_ndft3 = toc(t_fwd_ndft3_start);
    display(['Time for fwd ndft3: ' num2str(t_fwd_ndft3) ' s'])

    % Adjoint
    t_adj_ndft3_start = tic;
    ndft_adjoint(plan);
    t_adj_ndft3 = toc(t_adj_ndft3_start);
    display(['Time for adj ndft3: ' num2str(t_adj_ndft3) ' s'])

end
```

I'm considering to change the nfft_init_guru function in the following way:
For d>=2, always set the nfft_flag NFFT_OMP_BLOCKWISE_ADJOINT.

**Comment by aitkenap** [comment]
Thanks for the tips! I should have looked a bit more closely before copying the commented line.

The NFFT_OMP_BLOCKWISE_ADJOINT flag makes a big difference, the forward and adjoint times are now comparable. I also see almost no difference in speed between PRE_FULL_PSI vs PRE_PSI, even using the same plan for a couple of hundred cycles of forward/adjoint (which is our typical use case), so I'll stick to PRE_PSI.

**Comment by tvolkmer** [comment]
I'm going to leave the nfft_init_guru function as it is.

I added the constant (function) NFFT_OMP_BLOCKWISE_ADJOINT to the matlab interface which always returns 2^(12)=4096. This means your test script would look now like this:

```
clear all
close all

%% Parameters

N = 64;
sigma = 1.25;  % oversampling factor, typically >1
n = 2^(ceil(log2(sigma*N)));  % FFTW length, must be even integer, power of 2 suggested
m = 6;
n_reps = 1; % Number of times to run the fwd/adj tests

dims = 3;   % 2 or 3 for 2D/3D transform
DO_DFT = false; 

%% Initialize

switch dims
    case 2
        img = complex(phantom(N));
        % use nfft_flags PRE_PHI_HUT, PRE_PSI, NFFT_OMP_BLOCKWISE_ADJOINT
        plan = nfft(2,[N;N],N^2,n,n,m, ...
        bitor(PRE_PHI_HUT,bitor(PRE_PSI,NFFT_OMP_BLOCKWISE_ADJOINT)),FFTW_MEASURE);

    case 3
        img = repmat(complex(phantom(N)),[1 1 N]);
        % use nfft_flags PRE_PHI_HUT, PRE_PSI, NFFT_OMP_BLOCKWISE_ADJOINT
        plan = nfft(3,[N;N;N],N^3,n,n,n,m, ...
        bitor(PRE_PHI_HUT,bitor(PRE_PSI,NFFT_OMP_BLOCKWISE_ADJOINT)), ...
        FFTW_MEASURE);

    otherwise
        error('dims must be 2 or 3')

end

k = (rand(N^dims,dims)-0.5)*(1-eps);

plan.x = k;

%% NFFT

display(['NFFT (' num2str(dims) 'D, ' num2str(nfft_get_num_threads()) ' threads):'])

% Precomputation
t_precomp_start = tic;
nfft_precompute_psi(plan);
t_precomp = toc(t_precomp_start);

display(['Time for precomp: ' num2str(t_precomp) ' s'])

for ii = 1:n_reps

    % Forward
    plan.fhat = img(:);
    t_fwd_nfft3_start = tic ;
    nfft_trafo(plan);
    t_fwd_nfft3 = toc(t_fwd_nfft3_start);
    display(['Time for fwd nfft3: ' num2str(t_fwd_nfft3) ' s'])

    % Adjoint
    t_adj_nfft3_start = tic;
    nfft_adjoint(plan);
    t_adj_nfft3 = toc(t_adj_nfft3_start);
    display(['Time for adj nfft3: ' num2str(t_adj_nfft3) ' s'])

end


%% Direct

if DO_DFT
    display(['NDFT (' num2str(dims) 'D):'])

    % Forward
    plan.fhat = img(:);
    t_fwd_ndft3_start = tic;
    ndft_trafo(plan);
    t_fwd_ndft3 = toc(t_fwd_ndft3_start);
    display(['Time for fwd ndft3: ' num2str(t_fwd_ndft3) ' s'])

    % Adjoint
    t_adj_ndft3_start = tic;
    ndft_adjoint(plan);
    t_adj_ndft3 = toc(t_adj_ndft3_start);
    display(['Time for adj ndft3: ' num2str(t_adj_ndft3) ' s'])

end
```
