### ISSUE TITLE
Question: data dimension limit

### ISSUE THREAD

**Issue by PatrickSteinmueller** [NFFT/nfft#117]
Hi,

I am interested in using your library in a quantum computing context. We have a large body of data in a high dimensional space, that is not sampled in an equidistant grid (sobol sequences). However, most libraries for adjoint NFFTs seem to have a technical limit of only allowing three dimensional data.

As far as your publications go, I have not seen any limit described. Is there a technical limitation with regards to the dimension?

Kind Regards

Patrick Steinmüller

**Comment by michaelquellmalz** [comment]
Hi, the NFFT usually works well for dimensions up to d=5. I know of a practical application with d=4. 

There is no strict technical limit of the dimension (although the Matlab interface currently allows only d<=5). However, for higher dimensions the memory requirements become much bigger so that it seems usually not practical anymore (e.g. the number of Fourier coefficients is N^d).

For higher dimensions, one could work on different grids, for example [rank-one lattices](https://www-user.tu-chemnitz.de/~potts/paper/reco_indexset_incr.pdf).

**Comment by PatrickSteinmueller** [comment]
Hi Michael,

thanks for your answer. In our use case (Parametrized Quantum Circuit) the number of acceptable Fourier coefficients is restricted and usually much smaller than N^d.

I will have a look at the paper.

Kind Regards

Patrick Steinmüller
