### ISSUE TITLE
[Conventions] Utility software for meeting requirements of CONVENTIONS.md?

### ISSUE THREAD

**Issue by kevinmatthes** [NFFT/nfft#129]
Due to the ongoing discussion on further conventions, #120, I wondered if meeting the recent requirements according to `CONVENTIONS.md` might be easier if some software would check or rather optimise the code if required.

Especially regarding the question of trailing semicolons after closing curly brackets can be answered quite easily with a deterministic finite automaton in combination with according actions on the code, i. e. the removal of obsolete semicolons.  Shall I prepare such one?

**Comment by kevinmatthes** [comment]
Another benefit of such utility software would be that it might be set up together with the other automatic actions such that newly uploaded code would become optimised on arrival in the repository.  Although this might require a further commit (something like "Optimise code"), this procedure would make meeting the conventions much easier since we could rely on the utility software for optimisation.

**Comment by michaelquellmalz** [comment]
I would rather refrain from writing such a tool since doing so always opens up some possibility of unintentionally breaking some expected behavior or introducing some new bugs. Preventing such things would require much testing. Therefore I believe that the risks of such feature outweigh its benefits.
