### ISSUE TITLE
relocation against `fftw_solvtab_rdft_r2r' in read-only section `.text'

### ISSUE THREAD

**Issue by razgzy** [NFFT/nfft#136]
I‘ve tested the FFTW works properly by pyFFTW.
But failed when make file with errors below: 
```
/usr/bin/ld: /usr/local/lib/libfftw3.a(lt7-conf.o): warning: relocation against `fftw_solvtab_rdft_r2r' in read-only section `.text'
/usr/bin/ld: /usr/local/lib/libfftw3.a(assert.o): relocation R_X86_64_PC32 against symbol `stdout@@GLIBC_2.2.5' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: final link failed: bad value
collect2: error: ld returned 1 exit status
make[1]: *** [Makefile:662: libnfft3.la] Error 1
make[1]: Leaving directory '/raid/zhugezy/nfft-3.5.3'
make: *** [Makefile:716: all-recursive] Error 1
```
gcc (Ubuntu 11.3.0-1ubuntu1~22.04.1) 11.3.0
cmake version 3.26.4

**Comment by michaelquellmalz** [comment]
It looks like you built the FFTW yourself. As the error message says: In order to work with the NFFT, you need to compile the FFTW with the option `--with-pic` (for the `configure` script, but there should be an equivalent option for cmake to add the `-fPIC` to the CFLAGS).

Alternatively (which might be the better approach), you can compile the dynamic library of the FFTW and also the NFFT instead of the static library `.a` which you used. In particular compile the FFTW with the `--enable-shared` option, as stated in the NFFT Readme file, see also the [FFTW documentation](http://fftw.org/fftw3_doc/Installation-on-Unix.html#Installation-on-Unix).

**Comment by razgzy** [comment]
Thank you for your advice. I forgot adding --enable-shared. The problem has been solved now
