### ISSUE TITLE
Upgrade license from GPLv2 to GPLv2+ or GPLv3?

### ISSUE THREAD

**Issue by ghisvail** [NFFT/nfft#15]
Are there any specific rationales behind staying `GPLv2 only` as opposed to `GPLv2 or later` or `GPLv3`? `GPLv2 only` currently prevents NFFT being used in any projects which uses code licensed under `Apache v2`, which has become one of the most popular permissive license in open-source.

**Comment by tvolkmer** [comment]
As far as I know, the NFFT3 library should be `GPLv2 or later`. What am I missing?

The README states:

`NFFT3 is free software. You can redistribute it and/or modify it under the`
`terms of the GNU General Public License as published by the Free Software`
`Foundation; either version 2 of the License, or (at your option) any later`
`version. If not stated otherwise, this applies to all files contained in this`
`package and its sub-directories.`

All source files should contain the following copyright message:

`/*`
` * Copyright (c) 2002, 2015 Jens Keiner, Stefan Kunis, Daniel Potts`
` *`
` * This program is free software; you can redistribute it and/or modify it under`
` * the terms of the GNU General Public License as published by the Free Software`
` * Foundation; either version 2 of the License, or (at your option) any later`
` * version.`
`.............`

**Comment by ghisvail** [comment]
My bad, sorry for the noise. Closing.
