### ISSUE TITLE
Unit tests fail when using OpenMP with certain window function(s).

### ISSUE THREAD

**Issue by jenskeiner** [NFFT/nfft#2]
There seems to be a problem when using OpenMP and certain window functions. Some unit tests cases fail indicating a bug.

**Comment by tvolkmer** [comment]
Which tests fail and how much are the measured errors above the threshold value?

When I tested the OpenMP version, I sometimes encountered an approximation error which was about 10-20% higher than the single thread version.

**Comment by jenskeiner** [comment]
Tests seem to fail only where M > 1. Where they fail the error is not just off by small margin but substantial, indicating that they are completely broken. Several window function/floating-point type combinations seem to be affected, though not all.

I have pushed the branch feature/2-fix-openmp where I have enabled openMP in .travis.yml. Details about the failing cases can be found in the Travis CI results; see https://travis-ci.org/NFFT/nfft_new/.

**Comment by jenskeiner** [comment]
I've updated .travis.yml so that we don't compile the OpenMP support for clang anymore.

**Comment by tvolkmer** [comment]
The problems should be fixed now. There were two issues:

1. The errors with the bspline and sinc window functions were caused by the usage of a temporary working array `spline_coeffs` in the struct `nfft_plan` by multiple threads.
2. The double precision functions `creal` and `cimag` were still used inside the nfft kernel instead of the multiprecision macros `CREAL` and `CIAMG`. The failed tests, especially in the single / long double precision case, could also be caused by a compiler problem in combination with the `creal` and `cimag` calls, see below.

Open issue:
3. Another possible problem is that the runtimes seem to be very bad in single precision compared to double / long double precision.

ad 1.) When I implemented the OpenMP support, I didn't have a closer look at the bspline window function and the field `spline_coeffs` of `nfft_plan` in `include/nfft3.h`:
`  R *spline_coeffs; /**< input for de Boor algorithm, if B_SPLINE or SINC_2m is defined   */\`
I thought that these are some precomputed values, but instead this apparently is a temporary working array, which is called `scratch` inside the `nfft_bspline` function in `kernel/util/bspline.c` and is even completely zeroed in the function. Of course, using an identical working array in different threads is a very bad idea.
In the current bugfix, I removed this array from the `nfft_bspline` function and added the definition
`  R scratch[k];`
at the beginning. Additionally, I renamed the function `nfft_bspline` to  `nfft_bsplines`.
@jenskeiner Please verify this change and the size `k` of the `scratch` array.
One possible issue is that the function was renamed and, in theory, we should increase the major version of the `libnfft3.so` file. The good news is that the function `nfft_bsplines` is "internal" (only defined in `include/infft.h`), which means I would prefer to stay at `libnfft3.so.2`. For compability reasons, I kept the field
`  R *spline_coeffs; /**< input for de Boor algorithm, if B_SPLINE or SINC_2m is defined   */\`
in the plans. However, we should remove them in the next major release nfft-3.4 (or this will be obsolete if we switch to opaque plan pointers).

ad 2.) The issue with the non-working OpenMP in single and long double precision was quite strange. On my 64-bit openSUSE 13.1 with GCC 4.8.1 everything seemed to work fine. However, on 32-bit Scientific Linux 6.5 with GCC 4.4.7 as well as 64-bit travis-ci with GCC 4.6.3, the tests failed. Therefore, I think this might also be partially a problem with the used compiler. The problem occurred in the adjoint nfft in one of two approaches. For the adjoint nfft, I have implemented two different approaches, cf. [NFFT OpenMP Parallelization](http://www.tu-chemnitz.de/~potts/paper/openmpNFFT.pdf) Section 4.2.5. Both target the multiplication with the matrix B^T (multiplication with the window function in spatial domain). In this step, the input data is `plan.f` (of length `M_total` = number of nodes) and the output data is `plan.g` (of length `n_total` = oversampled FFT length). The index, where the threads need to add some value in `plan.g`, depends on the location on the spatial nodes `plan.x`.
- Approach A, where the problem occurred, (default in 1d simple init or `init_guru` without flag `NFFT_OMP_BLOCKWISE_ADJOINT`) uses a `for` loop over the nodes `plan.x` / the input `plan.f` and accumulates on the output `plan.g`, where the write operations are arbitrated using the OpenMP pragma `atomic`:
```
  #pragma omp parallel for default(shared) private(k)
  for (k = 0; k < M; k++)
  {
    INT l;
    INT j = k;
    for (l = 0; l < lprod; l++)
    {
      C val = psi[j * lprod + l] * f[j];
      C *gref = g + psi_index_g[j * lprod + l];
      R *gref_real = (R*) gref;

      #pragma omp atomic
      gref_real[0] += CREAL(val);

      #pragma omp atomic
      gref_real[1] += CIMAG(val);
    }
  }
```
In the problematic version, the first atomic operation was
```
      #pragma omp atomic
      gref_real[0] += creal(val);
```
On the left-hand side, there was a multi-precision real data type and on the right-hand side a double data type. Now with multi-precision real data types on both sides, everything seems to work.
- Approach B (default for d>2 simple init or `init_guru` with flag `NFFT_OMP_BLOCKWISE_ADJOINT`) uses a different scheme. The nodes `plan.x` / inputs `plan.f` are sorted by their index in the output `plan.g` and the for loop runs over the index in `plan.g`.

Some simple benchmarks `examples/nfft/nfft_benchomp` suggest that in 1d apprach A might be faster and for d>1 approach B. This is the reason for the chosen default.

ad 3.) The runtimes of the test builds are similar for double precision and long double precision but seem to take much more time for single precision. Currently, I'm not sure why.

**Comment by jenskeiner** [comment]
Thanks for the detailed analysis and for fixing the issue.

1. I think we can work with the proposed solution, but we should be aware that moving the scratch space into the method could degrade performance if the compiler is not smart enough to avoid allocation of it for each method call. If so, it should be moved outside again and made thread-private.

2. There could be compiler bugs, definitely. But if fixing our code to what it should have been in the first place solves the problem, then that's close enough for me.

3. I have noticed the same differences as well. It's not too surprising to see that double and long double behave the same. After all, on x86 architectures, the CPU typically uses extended precision (aka long double) internally anyway. so differences can mainly be attributed to a longer choice of the cut off parameter, I guess. Note that this might still be different on other architectures, we're just not testing on these. Regarding single precision (aka float), it could be difficult to find out why exactly everything seems to be slower. Could be that modern CPUs are no longer optimized for single precision, or maybe we're not correctly aligning the arrays in memory, thereby preventing auto-vectorization. Thoughts welcome.

**Comment by tvolkmer** [comment]
ad 3.) I ran the OpenMP benchmarks `examples/nfft/nfft_benchomp` on a 12 core x64 CPU. The measured times show the expected results, the 32-bit single precision version is about 30 % faster than the 64-bit double precision version at 1 thread, see the attached files. (Sorry, you need to compare both documents page-by-page).

[benchomp_double.pdf](https://github.com/NFFT/nfft/files/164928/benchomp_double.pdf)
[benchomp_single.pdf](https://github.com/NFFT/nfft/files/164929/benchomp_single.pdf)

**Comment by jenskeiner** [comment]
So it’s likely that with Travis CI we are seeing some effects from the virtualized environment. The unit tests run in a Docker container and maybe some virtualization layers are not very efficient when it comes to single precision. In any case, we shouldn’t worry.

**Comment by jenskeiner** [comment]
Closing this one.
