### ISSUE TITLE
Missing FFTW 3 library for the NFFT Matlab interface?

### ISSUE THREAD

**Issue by andreydung** [NFFT/nfft#21]
I installed fftw3 and set the path correctly:

`./configure --with-fftw3=/usr/local --with-fftw3-libdir=/usr/local/lib --with-fftw3-includedir=/usr/local/include --with-matlab=/usr/local/MATLAB/R2014a --with-matlab-fftw3-libdir=/usr/local/lib`

returns error:

```
checking for /usr/local/MATLAB/R2014a/bin/glnxa64/libmx.so... yes
checking for mexCallMATLAB in -lmex... no
checking for /usr/local/MATLAB/R2014a/bin/glnxa64/libmex.so... yes
checking for matGetVariable in -lmat... no
checking for /usr/local/MATLAB/R2014a/bin/glnxa64/libmat.so... yes
checking for /usr/local/MATLAB/R2014a/extern/src/mexversion.c... no
configure: WARNING: File /usr/local/MATLAB/R2014a/extern/src/mexversion.c not found
checking for Matlab fftw3 library... no
checking for Matlab fftw3 library (-lm set)... no
checking for Matlab fftw3 library (-lpthread -lm set)... no
configure: error: You don't seem to have installed the FFTW 3 libray for the NFFT Matlab interface.
```

In config.log, it says that cannot find -lmwfftw3. 

How do I fix this issue? I'm on Ubuntu 14.04 64bit

**Comment by ghisvail** [comment]
```
--with-matlab-fftw3-libdir=/usr/local/lib
```
and
```
checking for Matlab fftw3 library... no
checking for Matlab fftw3 library (-lm set)... no
checking for Matlab fftw3 library (-lpthread -lm set)... no
```
What else do you need ? The log is self-explanatory.

Either use your local copy of FFTW under `/usr/local/lib` or use MATLAB's, which is **not** under `/usr/local/lib` but probably somewhere under `/usr/local/MATLAB/R2014a`...

**Comment by ghisvail** [comment]
you may run `find /usr/local/MATLAB/R2014a -name "*mwfftw*"  to get the exact path to your MATLAB's FFTW binary.`

**Comment by tvolkmer** [comment]
Without having more information, it is hard for me to guess what the problem is.

One typical cause for this issue is that you have not installed both the static (`libfftw3.a`) and dynamic (`libfftw3.so`) FFTW library.

Please check your `/usr/local/lib` directory for
   `libfftw3.a`
and
   `libfftw3.so`

By default the NFFT3 `configure` / `make` script try to compile both the static and dynamic version of the NFFT3 library.

If you have compiled and installed the FFTW library yourself, please do this again with the `configure` option `--enable-shared`

Alternatively, please try to run the NFFT3 `configure` script with the option `--disable-shared`

**Comment by jenskeiner** [comment]
For the Matlab interface, we need to link against the Matlab provided versions of FFTW. In your case, we look for these under /usr/local/MATLAB/R2014a/bin/glnxa64/. Please check if you can find the FFTW libraries there.

**Comment by andreydung** [comment]
Fixed! I'm just wondering, what is the difference between **libfftw3** and **limbwfftw3**? Is the later coming from Matlab itself, not from fftw.org?

**Comment by jenskeiner** [comment]
The versions in the Matlab folder are shipped by the vendor. They might not be identical to the plain vanilla libraries which is why we always link against them for the Matlab interface.
