### ISSUE TITLE
/usr/bin/ld: fastsumS2.o: undefined reference to symbol 'cos@@GLIBC_2.2.5'

### ISSUE THREAD

**Issue by ghisvail** [NFFT/nfft#6]
I get the following undefined reference when building the 3.3.0.alpha1 tag with examples and applications on my Linux machine. Probably due to an ```-lm``` link flag missing somewhere.

**Comment by jenskeiner** [comment]
libnfft.la depends on libm, so libtool should take care of adding -lm.
Toni: Is this the same problem with a certain libtool patch we were looking at recently?

**Comment by tvolkmer** [comment]
Yes, this is the same problem with the patched libtool version of Debian/Ubuntu. I added the -lm to fastsumS2 and others. This issue should be fixed.
Ghisvail: Could you please verify if compiling the examples and applications works now?

**Comment by ghisvail** [comment]
Thanks Toni. Will be trying this out today.

**Comment by ghisvail** [comment]
Just as a side note:
You are probably refering to [this](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=702737) problem.

Some solutions:
http://lists.lttng.org/pipermail/lttng-dev/2012-August/018337.html
http://git.lrde.epita.fr/?p=spot.git;a=commitdiff;h=0e74b76521341f670f6b76f8ef24a6dcf6e3813b

Since it is Debian specific, I am happy to leave this fix downstream and keep the code tree as it were before. Your call guys.

**Comment by tvolkmer** [comment]
Yes, that's exactly the problem. Thank you for giving us the second solution, I haven't known that one yet with setting
   link_all_deplibs=yes
   link_all_deplibs_CXX=yes
in configure.ac.
Jens: What's your preferred solution?
- Keep the (5 or 6) added "-lm" flags in the Makefile.am files
or
- set these two lines (I think the first one is sufficient for us since we only use C) in configure.ac?

**Comment by jenskeiner** [comment]
> Am 15.01.2015 um 12:25 schrieb Toni Volkmer <notifications@github.com>:
> 
> Yes, that's exactly the problem. Thank you for giving us the second solution, I haven't known that one yet with setting
> link_all_deplibs=yes
> link_all_deplibs_CXX=yes
> in configure.ac.
> Jens: What's your preferred solution?
> 
> Keep the (5 or 6) added "-lm" flags in the Makefile.am files or
> set these two lines (I think the first one is sufficient for us since we only use C) in configure.ac?

I would prefer the second solution. Maybe keep the second line as well just in case somebody must use a C++ compiler.

However, I thought there was also a third option: Defining libm as a direct dependency of libnfft (I think I removed it at one point), rather than relying on the transitive dependency via fftw. I would like to think that libtool would add -lm everywhere where we also link libnfft. Can you check?

**Comment by ghisvail** [comment]
@tvolkmer 
You're very welcome.

@jenskeiner 
Applications, examples and tests now build fine with the current alpha-2.

The tags are messed up btw, they provide the source tree under a subdirectory (nfft-3.3) as opposed to leave everything in root. Right now, I am creating the release tarball manually with ```git archive``` based on the commit the tag was supposed to be made, but it would be nice if you guys could fix that for subsequent releases.

**Comment by jenskeiner** [comment]
Will fix it.
