### ISSUE TITLE
Single-precision testsuite fails for many architectures including i386

### ISSUE THREAD

**Issue by jenskeiner** [NFFT/nfft#6]
Transferred from: https://github.com/NFFT/nfft_old/issues/17

Since enabling the testsuite for the single and long-double precision as part of the package build process, the builders have reported [multiple failures](https://buildd.debian.org/status/package.php?p=nfft&suite=experimental).

I would not have worried if these failures were restricted to some exotic architectures, but here even the standard 32-bit `i386` fails to pass the single-precision tests. I can disable the single precision testsuite temporarily but it would be nice to investigate the cause for this.

**Comment by ghisvail** [comment]
Still happening for version `3.3.1rc1`. The minimum should be to have both double and single precision builds of `nfft` pass on all architectures. Right now, this is the case for double not for single.

The strange thing is that the testsuite for single fails on [`i386`](http://debomatic-i386.debian.net/distribution#unstable/nfft/3.3.1~rc1-1/buildlog) but passes on [`armel`](http://debomatic-armel.debian.net/distribution#unstable/nfft/3.3.1~rc1-1/buildlog) and [`armhf`](http://debomatic-armhf.debian.net/distribution#unstable/nfft/3.3.1~rc1-1/buildlog). Could well be just due to a tolerance error set too strictly?

**Comment by jenskeiner** [comment]
Very likely that the bounds need some adjustments. Possible to get the full terminal output for each failing arch?

**Comment by ghisvail** [comment]
> Possible to get the full terminal output for each failing arch?

They are available in the logs I linked earlier. The output is quite long so I'd rather not try to duplicate it here.

**Comment by jenskeiner** [comment]
Will have a look. Thanks.

**Comment by jenskeiner** [comment]
Yes, the NFFT build fails on i386, but the issue is actually in a helper function used to evaluate B-splines, not in one of the core modules. The relative error is off by a large margin in some cases (high degree). This warrants a closer look as it could indicate a bug.

The armel and armhf builds do not seem to fail when building NFFT. The corresponding build steps are ticked off and the log looks ok. The issue seems to be in the fenix-plugins step.

**Comment by ghisvail** [comment]
Let me know if you need more input, although the verbosity of the build was made maximum already.

**Comment by jenskeiner** [comment]
G’day,

I’m able to reproduce the i386 problem in a VM. I’ll look into it. I understand that you are looking at the other failing architectures since the issues there don’t seem to be NFFT related.

Best,


Jens

**Comment by ghisvail** [comment]
@jenskeiner you may close this issue.

**Comment by jenskeiner** [comment]
Will do.
