### ISSUE TITLE
NFFT normalization

### ISSUE THREAD

**Issue by SylvainLan** [NFFT/nfft#74]
Hello, 

I have been searching for a bit about the normalization for the NFFT, I'm using it with matlab and python and am computing operations where I have to apply recursively the NFFT and its adjoint but if I don't take care the norm of the iterate explodes.

What is a good way to normalize the transform so that the norm of the input equals the norm of the output ? 

I'm sorry to post this issue here but I was hoping you could help !

**Comment by jenskeiner** [comment]
Dear Sylvain,

thanks for your message. I’m not in a position to look at he code, but it should be quite easy to work out the correct normalization. If you look at the definition at https://www-user.tu-chemnitz.de/~potts/nfft/ you can see that the NFFT is roughly the same as an (inverse) DFT, just with unequal nodes. If you take equally-spaced nodes, then the NFFT just becomes a regular (inverse) DFT. Then, we know that if you apply the forward and then the inverse transformation, you need to scale the result by 1/n (n = number of nodes) to obtain back the original input. Like you stated, for more than one dimension, the normalization factor becomes one over the product of the lengths across each dimension.

It’s a matter of taste whether you apply the normalization just once or if you take the square root and apply it after each transform, the result would be the same.

I’m not sure what the issue is in your case, but you can easily verify the NFFT Library’s correctness by calculating transforms with regularly-spaced nodes and checking that the expected normalization factors apply. Remember that for equispaced nodes, the adjoint transform is (up to normalization) the inverse transform. If that works out ok, then the normalization will be the same for non-equispaced nodes, but you will of course loose the property that the adjoint transform is the inverse.

Let us know what you think,


Jens
